# Generated by Django 3.2 on 2021-04-15 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, null=True, verbose_name='Apellidos')),
                ('tipodocumento', models.CharField(choices=[('1', 'Órgano regulador'), ('2', 'Directorio'), ('3', 'Gerencia'), ('4', 'Negocio'), ('5', 'Mejora Interna')], max_length=20, null=True, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=11, verbose_name='Documento')),
                ('telefono_principal', models.CharField(max_length=10, verbose_name='N° Celular')),
                ('telefono_secundario', models.CharField(max_length=10, verbose_name='N° Teléfono')),
                ('email', models.EmailField(max_length=60, verbose_name='Correo Electrónico')),
                ('fecha', models.DateField(auto_now=True, null=True)),
                ('hora', models.TimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=False, verbose_name='¿Activo?')),
            ],
            options={
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='PersonalUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, null=True)),
                ('hora', models.TimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=False, verbose_name='¿Activo?')),
                ('usuariopersonal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal de Usuario',
                'verbose_name_plural': 'Personal de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajador', models.CharField(choices=[('1', 'Empleado'), ('2', 'Obrero')], max_length=20, null=True, verbose_name='Tipo de Trabajador')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('fecha', models.DateField(auto_now=True, null=True)),
                ('hora', models.TimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=False, verbose_name='¿Activo?')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Projects.persona')),
            ],
            options={
                'ordering': ['tipo_trabajador'],
            },
        ),
    ]
