# Generated by Django 3.2 on 2021-04-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20210415_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=200, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(choices=[('1', 'Soltero'), ('2', 'Casado'), ('3', 'Viudo'), ('4', 'Divorciado')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipodocumento',
            field=models.CharField(choices=[('1', 'DNI'), ('2', 'CARNET DE EXTRANJERIA'), ('3', 'PASAPORTE'), ('4', 'OTRO')], max_length=20, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
