# Generated by Django 3.2 on 2021-04-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_alter_persona_telefono_secundario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=10, verbose_name='N° Teléfono'),
        ),
    ]
