# Generated by Django 3.2 on 2021-04-16 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0005_alter_persona_telefono_secundario'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalusuario',
            name='personal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Projects.personal', verbose_name='Personal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalusuario',
            name='usuariopersonal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
